name: autotests
on:
  - workflow_dispatch
jobs:
  git-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: dependencies
      run: |
        python -m ensurepip
        python -m pip install -U uv
        python -m uv venv
        python -m uv pip install -r pyproject.toml --extra=tests --python=.venv/bin/python
    - name: tests
      run: tg_session=${{ secrets.git_linux }} big_tests=true .venv/bin/python reposter

  git-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: dependencies
      run: |
        python -m ensurepip
        python -m pip install -U uv
        python -m uv venv
        python -m uv pip install -r pyproject.toml --extra=tests --python=.venv/scripts/python.exe
    - name: tests
      run: |
        $env:tg_session = '${{ secrets.git_win }}'
        $env:big_tests = 'true'
        .venv/scripts/python reposter

  bat-pypi-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: tests
      run: |
        $env:tg_session = '${{ secrets.bat_pypi_win }}'
        $env:big_tests = 'true'
        cd other/launcher
        cmd /c reposter.bat

